version: '3.8'

services:
  # Laravel App
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: spmb-app
    container_name: spmb_app
    restart: unless-stopped
    working_dir: /var/www
    # Meneruskan variabel dari .env lokal ke dalam container
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/storage:/var/www/storage
      - ./backend/.env:/var/www/.env
    networks:
      - spmb-network

  # Nginx
  web:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: spmb_web
    restart: unless-stopped
    ports:
      - "8002:80"
    depends_on:
      - app
    networks:
      - spmb-network

  # PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: spmb_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: spmb_smk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-buhun666}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - spmb-network

networks:
  spmb-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
